# Generated by Django 3.2.13 on 2022-07-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('weight', models.CharField(choices=[('kg', 'kilogram'), ('g', 'gram'), ('l', 'litre'), ('ml', 'millilitre'), ('pcs', 'pieces')], default='kg', max_length=5)),
            ],
        ),
    ]
