# Generated by Django 3.2.13 on 2022-07-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0002_auto_20220715_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(choices=[('kg', 'kilogram'), ('g', 'gram'), ('l', 'litre'), ('ml', 'millilitre'), ('pc', 'piece'), ('tablespoon', 'tablespoon'), ('cup', 'cup'), ('teaspoon', 'teaspoon')], default='kg', max_length=10),
        ),
    ]
