# Generated by Django 3.2.13 on 2022-07-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0004_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='count',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(choices=[('kg', 'kilogram'), ('g', 'gram'), ('l', 'litre'), ('ml', 'millilitre'), ('pc', 'piece'), ('tablespoon', 'tablespoon'), ('cup', 'cup'), ('teaspoon', 'teaspoon'), ('ounce', 'ounce')], default='kg', max_length=10),
        ),
    ]
