# Generated by Django 3.2.13 on 2022-07-16 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0005_auto_20220715_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='weight',
            new_name='unit_of_measurement',
        ),
        migrations.RemoveField(
            model_name='product',
            name='count',
        ),
    ]
