# Generated by Django 3.2.13 on 2022-07-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0006_auto_20220716_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
