# Generated by Django 3.2.13 on 2022-07-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('unit_of_measurement', models.CharField(choices=[('kg', 'kilogram'), ('g', 'gram'), ('l', 'litre'), ('ml', 'millilitre'), ('pc', 'piece'), ('tablespoon', 'tablespoon'), ('cup', 'cup'), ('teaspoon', 'teaspoon'), ('ounce', 'ounce')], default='kg', max_length=10)),
            ],
        ),
    ]
